# NumPy

In [3]:
import numpy as np

In [10]:
np.zeros([3,4], dtype=np.int32,)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [11]:
np.ones([3,4])

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [9]:
np.identity(10)

array([[ 1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.]])

In [12]:
a = np.arange(10)

In [13]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [15]:
b = a

In [16]:
a + b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [17]:
a + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

In [18]:
a = a.reshape(2,5)

In [19]:
a + 100

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109]])

In [21]:
sum(a)

array([ 5,  7,  9, 11, 13])

In [22]:
a = a + 100

In [23]:
a

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109]])

In [24]:
a = sum(a)

In [25]:
a

array([205, 207, 209, 211, 213])

In [26]:
np.array([[100,100], [100,100]]) - np.array([1,2])

array([[99, 98],
       [99, 98]])

In [27]:
np.array([[100,100], [100,100]]) - np.array([[1],[2]])

array([[99, 99],
       [98, 98]])

In [28]:
type(a)

numpy.ndarray

In [29]:
type(a.sum)

builtin_function_or_method

In [31]:
x = np.arange(25).reshape(5,5)

In [32]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [33]:
x.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [34]:
x.argmin(axis=0)

array([0, 0, 0, 0, 0], dtype=int64)

In [35]:
x.argmax(axis=0)

array([4, 4, 4, 4, 4], dtype=int64)

In [36]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [37]:
x.argmax()

24

In [38]:
np.where(x == 12)

(array([2], dtype=int64), array([2], dtype=int64))

In [39]:
np.where(x == 21)

(array([4], dtype=int64), array([1], dtype=int64))

In [41]:
x.cumsum(axis=0)

array([[ 0,  1,  2,  3,  4],
       [ 5,  7,  9, 11, 13],
       [15, 18, 21, 24, 27],
       [30, 34, 38, 42, 46],
       [50, 55, 60, 65, 70]], dtype=int32)

In [42]:
x.cumsum(axis=1)

array([[  0,   1,   3,   6,  10],
       [  5,  11,  18,  26,  35],
       [ 10,  21,  33,  46,  60],
       [ 15,  31,  48,  66,  85],
       [ 20,  41,  63,  86, 110]], dtype=int32)

In [43]:
x.mean(axis=0)

array([ 10.,  11.,  12.,  13.,  14.])

# Numpy vs List

In [52]:
a = np.arange(10000)
b = range(10000)

In [53]:
sum(b)

49995000

In [54]:
a.sum()

49995000

In [55]:
np.sum(a)

49995000

In [56]:
timeit(sum(b))

227 µs ± 13.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [57]:
timeit(a.sum())

7.69 µs ± 798 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# Slicing

numpyarray[row_from:row_to, col_from:col_to]

In [61]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [62]:
x[0:3, 3:5]

array([[ 3,  4],
       [ 8,  9],
       [13, 14]])